// import { Antonio, Roboto } from "next/font/google";
// import "./globals.css";


// const antonio = Antonio({
//   variable: "--font-antonio",
//   subsets: ["latin"],
//   weight: ["400", "700"] // চাইলে weight customize করো
// });
// const roboto= Gust({
//   variable:"--font-roboto",
//   subsets:["latin"],
//   weight:["400","700"]
// })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${antonio.variable} ${roboto.variable}  antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}





